---
config:
  COM_PORT: "AUTO"
  THEME: AMD
  HW_SENSORS: AUTO
  ETH: ""
  WLO: ""
  CPU_FAN: AUTO
  PING: ""
  WEATHER_API_KEY: ""
  WEATHER_LATITUDE: 45.75
  WEATHER_LONGITUDE: 4.85
  WEATHER_UNITS: metric
  WEATHER_LANGUAGE: en

display:
  REVISION: C_USB
  BRIGHTNESS: 30
  DISPLAY_REVERSE: false
  RESET_ON_STARTUP: false

multi-display:
  - DEVICE: 0
    VIDEO: "res/videos/Shiro Video Vertical 4.mp4"
    RESTART_MINUTES: 2
    REINIT_MINUTES: 3
    REVISION: C_USB
    DISPLAY_REVERSE: true
    BRIGHTNESS: 30
  - DEVICE: 1
    THEME: shiro-system
    REVISION: C_USB
    DISPLAY_REVERSE: false
    BRIGHTNESS: 30
  - DEVICE: 2
    IMAGE: res/images/shiro-image-horiz-06.png
    REVISION: C_USB
    DISPLAY_REVERSE: false
    BRIGHTNESS: 30
